#!/bin/bash

#####################################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  █████╗    #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔══██╗   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║  ╚═╝   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║  ██╗   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚█████╔╝   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚════╝    #
#####################################################################

$HOME/.config/bspwm/startup/desktop-startup &
$HOME/.config/bspwm/startup/picom-startup &
$HOME/.config/bspwm/startup/apps-startup &
$HOME/.config/bspwm/startup/polybar-startup &
$HOME/.config/bspwm/startup/bspwm-screen-startup &
$HOME/.config/bspwm/startup/bspwm-config-startup &
