#!/bin/bash

#  █▄▄ █▀ █▀█ █ █ █ █▀▄▀█   █▀ █▀▀ █▀█ █▀▀ █▀▀ █▄ █   █▀▀ █▀█ █▄ █ █▀▀ █ █▀▀
#  █▄█ ▄█ █▀▀ ▀▄▀▄▀ █ ▀ █   ▄█ █▄▄ █▀▄ ██▄ ██▄ █ ▀█   █▄▄ █▄█ █ ▀█ █▀  █ █▄█
# ---------------------------------------------------------------------------

if type "xrandr"; then

  MONITORS=$(xrandr --query | grep " connected" | grep "+" | cut -d" " -f1 | tr '\n' ' ');
  IFS=' ' read -r -a ARR_MONITORS <<< "$MONITORS"

  bspc wm -O $MONITORS
  bspc monitor ${ARR_MONITORS[0]} -d I II III IV V VI VII VIII

  if [ ${ARR_MONITORS[1]} ]; then
    bspc monitor ${ARR_MONITORS[1]} -d IX X XI XII XIII XIV XV XVI
  fi

else
  bspc monitor -d I II III IV V VI VII VIII
fi
